package MonthlyChallenges.September;

public class FindTheDifference {
    public static void main(String[] args) {
        FindTheDifference solution = new FindTheDifference();
        String test00 = "abcd";
        String test01 = "abcde";
        System.out.println(solution.findTheDifference(test00, test01));

        String test10 = "abcd";
        String test11 = "ecdba";
        System.out.println(solution.findTheDifference(test10, test11));
    }

    /**
     * Returns a character in "t" that was added to a string "s".
     *
     * Complexity - O(N)
     * Memory - O(1)
     *
     * @param s - original string.
     * @param t - a string that is generated by random shuffling string s and then add one more letter at a random
     *          position.
     * @return - the letter that was added in t.
     */
    public char findTheDifference(String s, String t) {
        int xor = 0;

        for (char ch : s.toCharArray()) {
            xor ^= ch;
        }
        for (char ch : t.toCharArray()) {
            xor ^= ch;
        }

        return (char) xor;
    }
}
